CREATE TABLE auth_provider
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_auth_provider PRIMARY KEY (id)
);

ALTER TABLE auth_provider
    ADD CONSTRAINT uc_auth_provider_name UNIQUE (name);